import React from 'react';


// Added by Salwa
const REGISTER_URL = "https://auth.moappetit.com/v1/signup"; // Signup end point

// Function to send a request to API to register user
const registerAPI = async (data) => {
  let requestOptions = {
    method: "POST",
    headers: {
        "Content-Type": "application/json"
    }
  };

  let body = {
    provider: "email",
    data: {
      email: data.email.toLowerCase(),
      password: data.password
    }
  };

  requestOptions.body = JSON.stringify(body);

  try {
    const response = await fetch(REGISTER_URL, requestOptions);
    return response; // Returning the response generated by the API
  } catch (e) {
    console.log("Request Failed: " + e.message);
  }
};

export default registerAPI;
// END: Added by Salwa
