// Added by Salwa
const SET_USER_URL = "https://data.moappetit.com/v1/query";

// Function to call the API that adds the user to the user_table in Hasura (postgres db)
export const setUserAPI = async (data) => {
    let requestOptions = {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        }
    };

    let body = {
        type: "insert",
        args: {
            table: "user_info",
            objects: [
                {
                    hasura_id: data.hasura_id,
                    name: (data.name).toLowerCase()
                }
            ]
        }
    };

    requestOptions.body = JSON.stringify(body);

    try {
        return await fetch(SET_USER_URL, requestOptions); // returning the response generated by the API
    } catch (e) {
        console.log('Request Failed:' + e);
    }
};

export default setUserAPI;

// END: Added by Salwa